const ENDPOINTS={
GET_MONTHWISE_FORM_DATA:'/getMonthwiseData',
CREATE_ACCOUNT:'/createAccount',
VERIFY_ACCOUNT: '/verifyAccount',
GET_FORM_DATA: '/getFormData',
GET_GRI1:'/getgri1',
GET_GRI2:'/getgri2',
GET_GRI3:'/getgri3',
GET_GRI5:'/getgri5',
GET_GRI6:'/getgri6',
CREATE_NEW_FORM:'/createnewform',
SUBMIT_FORM: '/submitForm',
RESUBMIT_FORM: '/submitFormRe',
APPROVE_FORM: '/approveForm',
DENY_FORM: '/denyForm',
SUBMIT_REMARK: '/submitRemark',
RESOLVE_REMARK: '/resolveRemark',
GET_MONTHWISE_APPROVED_DENIED_DATA: '/getMonthwiseADData',
GET_MONTHWISE_SUBMITTED_DATA:'/getMonthwiseSubData',
GET_MONTHWISE_RESUBMISSION_DATA: '/getMonthwiseResubData',
GET_REMARKS: '/getRemarks',
CHECK_EMAIL: '/checkEmail',
DELETE_PROFILE: '/deleteProfile',
FORGOT_PASSWORD: '/forgotPassword',
RESET_PASSWORD: '/resetPassword',
FETCH_DENIED_FORMS: '/fetchDeniedForms',
FETCH_MISSED_FORMS: '/fetchMissedForms',
GET_LOGS: '/getLogs',
GET_FORMS_STATUS: '/getFormStatus',
GET_FORM_STATS: '/getFormStats',
MAKE_LOG_ENTRY: '/makeLogEntry',
RAISE_TICKET: '/raiseTicket',
REVIEW_REQUEST: '/reviewReq',
ACCEPT_REQUEST: '/acceptReq',
DENY_REQUEST: '/denyReq'
}

export default ENDPOINTS;